server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    # React/Vite Router için yönlendirme (SPA kuralı)
    # Tüm URL'leri index.html'e yönlendir ki React Router çalışsın
    location / {
        try_files $uri $uri/ /index.html;
    }
}
